language: ruby
script:
    - bundle exec rake spec
    - bundle exec rake test
    - bundle exec rake metadata
    - bundle exec rake yamllint
rvm:
  - 2.0.0
  - 2.1.3
matrix:
  fast_finish: true
notifications:
  email: false
