HOSTS:
    # ubuntu-1404-x64:
    #     roles:
    #         - master
    #     platform: ubuntu-14.04-amd64
    #     box: ubuntu-14.04.1-beaker-amd64
    #     hypervisor: vagrant_parallels
    ubuntu:
        roles:
            - master
        platform: ubuntu-14.04-amd64
        image: ubuntu-upstart:14.04
        hypervisor: docker
        docker_cmd: ['/sbin/init']
        docker_preserve_image: true
        docker_image_commands:
             - wget --no-check-certificate https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
             - apt-get install -y wget ca-certificates
             - dpkg -i puppetlabs-release-trusty.deb
             - apt-get update
             - apt-get -y install puppet curl ntpdate git-core ruby
             - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"
CONFIG:
    type: foss
    log_level: verbose
